"""6 pre-loaded model conventions (best-practice templates from
ResourceContracts.org / AIPN / CNUCED / Vision minière africaine)."""
from typing import List, Dict


CONVENTION_MODELS: List[Dict] = [
    {
        "id": "model-aipn-psa",
        "name": "PSA modèle AIPN — Pétrole",
        "sector": "petrole",
        "source": "Association Internationale Pétrolière (AIPN)",
        "description": "Modèle de contrat de partage de production pour exploration et production pétrolières, équilibré entre droits de l'État souverain et investisseur.",
        "key_clauses": {
            "royalties": "8-12% selon zone et profondeur",
            "is": "30-35% (taux légal national)",
            "profit_oil_etat": "60-80% (échelle progressive)",
            "cost_oil_plafond": "50-70%",
            "duree": "25-30 ans renouvelable",
            "stabilisation": "limitée 5-7 ans, fiscalité uniquement",
            "arbitrage": "CIRDI ou CCI",
            "back_in_right": "≥15% à conditions de marché",
        },
        "compliance_score": 85,
        "tags": ["psa", "aipn", "best-practice", "petrole", "souverainete"],
    },
    {
        "id": "model-resourcecontracts-mining",
        "name": "Convention minière modèle ResourceContracts.org",
        "sector": "mines",
        "source": "Natural Resource Governance Institute (NRGI)",
        "description": "Modèle minier transparent, conforme ITIE et Vision minière africaine. Publication intégrale obligatoire.",
        "key_clauses": {
            "royalties": "5-8% selon minéral",
            "is": "25-30%",
            "duree": "20-25 ans renouvelable",
            "contenu_local": "≥40% en 10 ans",
            "emploi_local": "≥70% au-delà de 5 ans",
            "stabilisation": "absente ou limitée 5 ans",
            "transparence": "publication ITIE complète",
            "fonds_developpement_local": "≥1% du chiffre d'affaires",
        },
        "compliance_score": 90,
        "tags": ["mines", "nrgi", "resourcecontracts", "transparence", "itie"],
    },
    {
        "id": "model-cnudm-maritime",
        "name": "Convention maritime modèle CNUDM",
        "sector": "maritime",
        "source": "Convention de Montego Bay (CNUDM, 1982)",
        "description": "Modèle pour exploitation de la ZEE, pêche industrielle et exploration sous-marine. Préserve la souveraineté de l'État côtier.",
        "key_clauses": {
            "royalties_peche": "6-15% de la valeur des captures",
            "duree": "5-10 ans renouvelable annuellement",
            "quotas_captures": "obligatoires, scientifiques",
            "observateurs_embarques": "obligatoires",
            "transbordement": "ports nationaux uniquement",
            "souverainete_zee": "réaffirmée explicitement",
        },
        "compliance_score": 88,
        "tags": ["maritime", "cnudm", "zee", "peche", "souverainete"],
    },
    {
        "id": "model-redd-foret",
        "name": "Convention forestière modèle REDD+",
        "sector": "foret",
        "source": "ONU REDD+ / FAO",
        "description": "Modèle d'exploitation forestière durable avec mécanisme REDD+ (réduction émissions issues de la déforestation).",
        "key_clauses": {
            "royalties": "3-10% sur le bois exporté",
            "is": "25-30%",
            "rotation_coupe": "≥30 ans",
            "amenagement_durable": "plan d'aménagement obligatoire FSC ou PEFC",
            "redevances_carbone": "selon mécanisme REDD+",
            "concertation_communautes": "CLPE formalisé obligatoire",
            "monitoring_satellitaire": "obligatoire",
        },
        "compliance_score": 86,
        "tags": ["foret", "redd", "fao", "carbone", "communautes"],
    },
    {
        "id": "model-vma-african-mining",
        "name": "Convention Vision minière africaine (UA)",
        "sector": "mines",
        "source": "Union Africaine — Vision minière africaine 2009",
        "description": "Modèle aligné sur la VMA UA : transformation locale, contenu local, liens économiques, transfert technologique.",
        "key_clauses": {
            "royalties": "5-10%",
            "is": "30%",
            "valeur_ajoutee_locale": "≥50% à 15 ans",
            "transformation_minimum": "2e degré obligatoire en 10 ans",
            "transfert_tech": "programme formalisé avec bourses",
            "infrastructures_partagees": "obligatoires (rail, port, énergie)",
            "fonds_souverain_minier": "alimentation obligatoire",
        },
        "compliance_score": 92,
        "tags": ["mines", "vma", "afrique", "souverainete", "developpement"],
    },
    {
        "id": "model-cnuced-jv",
        "name": "Joint-Venture État-Entreprise modèle CNUCED",
        "sector": "mixte",
        "source": "CNUCED — Principes sur les contrats de ressources",
        "description": "Modèle de société mixte entre État (compagnie nationale) et investisseur étranger, avec gouvernance équilibrée.",
        "key_clauses": {
            "participation_etat": "≥35% (sans paiement initial)",
            "gouvernance": "conseil paritaire",
            "veto_etat": "sur décisions stratégiques",
            "transfert_tech": "obligation de transfert progressif",
            "rachat_etat": "option d'achat à valeur de marché",
            "audit_independant": "annuel obligatoire",
        },
        "compliance_score": 89,
        "tags": ["jv", "cnuced", "gouvernance", "souverainete"],
    },
]


# Pre-loaded sample contracts for demonstration (real well-known cases anonymized for educational use)
DEMO_CONVENTIONS = [
    {
        "id": "demo-tasiast-mauritanie",
        "name": "Démonstration — Tasiast (Mauritanie)",
        "country": "Mauritanie", "sector": "mines", "resource_type": "or",
        "company": "Major aurifère internationale",
        "year": 2017,
        "issues_detected": [
            "Stabilisation fiscale 25 ans (excessive)",
            "Royalties 4% sous-évaluées (benchmark 5-10%)",
            "Renonciation immunité d'exécution",
            "Confidentialité absolue (violation ITIE)",
        ],
    },
    {
        "id": "demo-simandou-guinee",
        "name": "Démonstration — Simandou (Guinée)",
        "country": "Guinée", "sector": "mines", "resource_type": "fer",
        "company": "Joint-venture mixte",
        "year": 2014,
        "issues_detected": [
            "Engagement infrastructure rail/port partagé",
            "Contenu local progressif 25→45%",
            "Transformation locale phase 2 obligatoire",
        ],
    },
    {
        "id": "demo-jubilee-ghana",
        "name": "Démonstration — Jubilee (Ghana)",
        "country": "Ghana", "sector": "petrole", "resource_type": "petrole",
        "company": "Consortium pétrolier",
        "year": 2007,
        "issues_detected": [
            "Cost oil plafond 80% (excessif)",
            "Profit oil État 50% (sous benchmark)",
            "Fonds souverain Heritage/Stabilization correctement configuré",
        ],
    },
    {
        "id": "demo-rovuma-mozambique",
        "name": "Démonstration — Rovuma LNG (Mozambique)",
        "country": "Mozambique", "sector": "gaz", "resource_type": "gaz_naturel",
        "company": "Consortium LNG",
        "year": 2018,
        "issues_detected": [
            "Stabilisation 25 ans",
            "Exemption TVA permanente",
            "Arbitrage CIRDI exclusif",
            "Bonus signature 50M USD (faible vs valeur du gisement)",
        ],
    },
    {
        "id": "demo-nlng-nigeria",
        "name": "Démonstration — NLNG (Nigeria)",
        "country": "Nigeria", "sector": "gaz", "resource_type": "gaz_naturel",
        "company": "JV État-Major",
        "year": 1989,
        "issues_detected": [
            "Pioneer status — 10 ans d'exemption fiscale",
            "Participation NNPC 49%",
            "Take-or-pay clauses",
            "Contentieux fiscal pluriannuel",
        ],
    },
    {
        "id": "demo-mauritania-senegal-gta",
        "name": "Démonstration — GTA (Mauritanie/Sénégal)",
        "country": "Mauritanie/Sénégal", "sector": "gaz", "resource_type": "gaz_naturel",
        "company": "Consortium opérateur",
        "year": 2019,
        "issues_detected": [
            "Accord d'unitisation transfrontalier",
            "Partage 50/50 entre les deux États",
            "Comité conjoint de pilotage",
            "Régime fiscal harmonisé",
        ],
    },
]
