"""Pre-loaded normative referential — Module 2 (Families 1-6)
+ International jurisprudence (ICSID, ICJ, African Court)
+ Doctrine principles D1-D8
+ Glossary (50+ terms)
"""
from typing import List, Dict


NORMATIVE_REFERENCES: List[Dict] = [
    # FAMILY 1 — DROIT INTERNATIONAL
    {"code": "N1.1", "family": 1, "title": "Résolution ONU 1803 (1962) — Souveraineté permanente sur les ressources naturelles",
     "summary": "Droit inaliénable des États à disposer librement de leurs richesses et ressources naturelles.",
     "test": "La convention garantit-elle la souveraineté permanente de l'État sur ses ressources ?"},
    {"code": "N1.2", "family": 1, "title": "Résolution ONU 3201 (1974) — Nouvel Ordre Économique International",
     "summary": "Droit à la nationalisation, contrôle des multinationales, partage équitable des bénéfices.",
     "test": "Partage équitable des bénéfices et contrôle des multinationales respectés ?"},
    {"code": "N1.3", "family": 1, "title": "Principes directeurs ONU Entreprises et Droits Humains (Ruggie, 2011)",
     "summary": "3 piliers : protéger, respecter, réparer. Mécanismes de recours pour communautés affectées.",
     "test": "Existence de mécanismes de recours pour les communautés affectées ?"},
    {"code": "N1.4", "family": 1, "title": "Convention de Montego Bay (CNUDM, 1982)",
     "summary": "Droits souverains de l'État côtier sur sa ZEE et son plateau continental.",
     "test": "Droits souverains de l'État côtier sur sa ZEE respectés ?"},
    {"code": "N1.5", "family": 1, "title": "Principes Équateur (2020)",
     "summary": "10 principes pour les projets > 10M USD : évaluation, gouvernance, transparence.",
     "test": "Projet conforme aux 10 principes Équateur ?"},
    {"code": "N1.6", "family": 1, "title": "Normes de performance IFC (2012) — 8 normes",
     "summary": "Évaluation risques, travail, ressources, santé, terres, biodiversité, patrimoine, autochtones.",
     "test": "Conformité aux 8 normes de performance IFC ?"},
    {"code": "N1.7", "family": 1, "title": "Principes OCDE sur la gouvernance des ressources naturelles",
     "summary": "Transparence, redevabilité, participation, gestion durable des recettes.",
     "test": "Gouvernance conforme aux principes OCDE ?"},
    {"code": "N1.8", "family": 1, "title": "Cadre ITIE — Initiative pour la Transparence des Industries Extractives",
     "summary": "Divulgation des paiements État-Entreprise. Publication obligatoire des contrats.",
     "test": "Convention conforme ITIE ? Clause de publication ?"},
    {"code": "N1.9", "family": 1, "title": "Convention de Bâle (1989) — Mouvements transfrontières de déchets dangereux",
     "summary": "Contrôle des mouvements et élimination des déchets dangereux.", "test": "Gestion conforme des déchets dangereux ?"},
    {"code": "N1.10", "family": 1, "title": "Accord de Paris (2015) — Climat",
     "summary": "Engagements de réduction des GES. CDN nationales.", "test": "Engagement climatique chiffré ?"},
    {"code": "N1.11", "family": 1, "title": "Convention sur la Diversité Biologique (CDB, 1992)",
     "summary": "Conservation, utilisation durable, partage juste des avantages.", "test": "Mesures de conservation de la biodiversité prévues ?"},
    {"code": "N1.12", "family": 1, "title": "Protocole de Nagoya (APA, 2010) — Accès et partage des avantages",
     "summary": "Partage juste et équitable des avantages issus des ressources génétiques.", "test": "Partage équitable des avantages prévu ?"},
    {"code": "N1.13", "family": 1, "title": "Convention CNUCC / Mérida (2003) — Anti-corruption",
     "summary": "Prévention, incrimination, coopération internationale, recouvrement d'avoirs.", "test": "Mécanismes anti-corruption prévus ?"},
    {"code": "N1.14", "family": 1, "title": "Principes CNUCED sur les contrats de ressources",
     "summary": "Transparence, équilibre, durabilité des contrats extractifs.", "test": "Contrat conforme aux principes CNUCED ?"},
    # FAMILY 2 — DROIT RÉGIONAL AFRICAIN
    {"code": "N2.1", "family": 2, "title": "Charte africaine des droits de l'homme et des peuples — Article 21",
     "summary": "Droit des peuples à disposer librement de leurs richesses et ressources naturelles. Récupération en cas de spoliation.",
     "test": "La convention dépossède-t-elle les populations de leurs ressources ?"},
    {"code": "N2.2", "family": 2, "title": "Vision minière africaine (2009, Union Africaine)",
     "summary": "Contenu local, valeur ajoutée nationale, liens économiques intersectoriels, transfert technologique.",
     "test": "Contenu local et valeur ajoutée nationale conformes à la VMA ?"},
    {"code": "N2.3", "family": 2, "title": "Code minier CEDEAO (cadre régional)",
     "summary": "Harmonisation des régimes miniers en Afrique de l'Ouest.", "test": "Conforme au cadre minier CEDEAO ?"},
    {"code": "N2.4", "family": 2, "title": "Traité OHADA — Droit des contrats et arbitrage CCJA",
     "summary": "Espace juridique unifié pour le droit des affaires en Afrique.", "test": "Clauses contractuelles compatibles avec OHADA ?"},
    {"code": "N2.5", "family": 2, "title": "APE / Accord de Cotonou ACP-UE",
     "summary": "Cadre commercial entre pays ACP et UE.", "test": "Compatibilité avec engagements ACP-UE ?"},
    {"code": "N2.6", "family": 2, "title": "Charte de l'énergie africaine (UA)",
     "summary": "Sécurité énergétique, intégration régionale, transition.", "test": "Compatible avec la charte énergétique UA ?"},
    {"code": "N2.7", "family": 2, "title": "Convention UA sur la prévention de la corruption (MACC)",
     "summary": "Mécanismes africains anti-corruption.", "test": "Garde-fous anti-corruption africains présents ?"},
    # FAMILY 4 — STANDARDS CONTRACTUELS INTERNATIONAUX
    {"code": "N4.1", "family": 4, "title": "Modèle PSA AIPN (Association Internationale Pétrolière)",
     "summary": "Modèle standard de contrat de partage de production.", "test": "Convention conforme aux standards AIPN ?"},
    {"code": "N4.2", "family": 4, "title": "Modèle convention minière ResourceContracts.org (NRGI)",
     "summary": "Modèle de bonne pratique pour conventions minières.", "test": "Convention conforme au modèle NRGI ?"},
    {"code": "N4.3", "family": 4, "title": "Principes CNUCED sur les contrats de ressources",
     "summary": "Lignes directrices pour des contrats équilibrés.", "test": "Conforme aux principes CNUCED ?"},
    {"code": "N4.4", "family": 4, "title": "Standards PWYP (Publiez Ce Que Vous Payez)",
     "summary": "Transparence des paiements des entreprises extractives.", "test": "Transparence PWYP respectée ?"},
    {"code": "N4.5", "family": 4, "title": "Normes ISO 14001 (Environnement) et ISO 26000 (RSE)",
     "summary": "Systèmes de management environnemental et responsabilité sociétale.", "test": "Engagement ISO 14001/26000 ?"},
    {"code": "N4.6", "family": 4, "title": "Lignes directrices OCDE pour les multinationales",
     "summary": "Conduite responsable des entreprises multinationales.", "test": "Conforme aux lignes directrices OCDE ?"},
    # FAMILY 5 — INDICATEURS DE RÉFÉRENCE SECTORIELLE
    {"code": "N5.1", "family": 5, "title": "Royalties pétrole brut : 5-25%",
     "summary": "Fourchette internationale pour les royalties pétrolières.", "test": "Royalties dans la fourchette ?"},
    {"code": "N5.2", "family": 5, "title": "Royalties or : 3-10%",
     "summary": "Fourchette internationale pour l'or.", "test": "Royalties or dans la fourchette ?"},
    {"code": "N5.3", "family": 5, "title": "IS secteur extractif Afrique : 25-35%",
     "summary": "Taux moyen de l'impôt sur les sociétés extractives en Afrique.", "test": "IS conforme à la moyenne régionale ?"},
    {"code": "N5.4", "family": 5, "title": "Contenu local Vision africaine : ≥ 50% en 15 ans",
     "summary": "Objectif de la Vision minière africaine.", "test": "Contenu local conforme à la VMA ?"},
    {"code": "N5.5", "family": 5, "title": "Partage de production PSA État : 60-80% profit oil",
     "summary": "Fourchette internationale pour le partage de production.", "test": "Part de l'État dans le profit oil conforme ?"},
    # FAMILY 6 — DOCTRINE
    {"code": "D1", "family": 6, "title": "Pacta sunt servanda vs Rebus sic stantibus",
     "summary": "Art. 26 vs Art. 62 Convention de Vienne. Renégociation pour changement fondamental de circonstances.",
     "test": "Application possible de la doctrine du changement fondamental ?"},
    {"code": "D2", "family": 6, "title": "Théorie de l'imprévision",
     "summary": "Bouleversement de l'économie du contrat → renégociation ou résiliation avec indemnisation.",
     "test": "Imprévision applicable ?"},
    {"code": "D3", "family": 6, "title": "Doctrine souveraineté permanente (Rés. 1803 ONU)",
     "summary": "Nul traité ne peut priver un État de sa souveraineté sur ses ressources naturelles.",
     "test": "Souveraineté permanente respectée ?"},
    {"code": "D4", "family": 6, "title": "Théorie des contrats léonins / clauses abusives",
     "summary": "Déséquilibre manifeste → nullité ou révision judiciaire.",
     "test": "Convention qualifiable de léonine ?"},
    {"code": "D5", "family": 6, "title": "Principe pollueur-payeur (Rio, Principe 16)",
     "summary": "Obligation de réparation intégrale par l'exploitant.", "test": "Pollueur-payeur appliqué ?"},
    {"code": "D6", "family": 6, "title": "Principe de précaution (Rio, Principe 15)",
     "summary": "Absence de certitude scientifique ne justifie pas l'inaction.", "test": "Précaution intégrée ?"},
    {"code": "D7", "family": 6, "title": "Doctrine de l'enrichissement sans cause",
     "summary": "Bénéfice excessif au détriment de l'État → restitution.", "test": "Enrichissement sans cause caractérisable ?"},
    {"code": "D8", "family": 6, "title": "Effet utile (ut res magis valeat quam pereat)",
     "summary": "Interpréter les clauses pour leur donner effet maximum dans le sens favorable aux populations.",
     "test": "Interprétation par effet utile possible ?"},
]


INTERNATIONAL_JURISPRUDENCE: List[Dict] = [
    {"tribunal": "CIRDI", "case_name": "Agip c. Congo", "year": 1979,
     "topic": "stabilisation",
     "ratio": "Limite de la nationalisation face aux clauses de stabilisation contractuelles."},
    {"tribunal": "Tribunal arbitral ad hoc", "case_name": "LIAMCO c. Libye", "year": 1977,
     "topic": "stabilisation",
     "ratio": "Portée des clauses de stabilisation en droit international."},
    {"tribunal": "Tribunal arbitral", "case_name": "Aminoil c. Koweït", "year": 1982,
     "topic": "nationalisation",
     "ratio": "Nationalisation légitime même avec clause de stabilisation, sous réserve d'indemnisation."},
    {"tribunal": "CIRDI", "case_name": "Metalclad c. Mexique", "year": 2000,
     "topic": "expropriation_indirecte",
     "ratio": "Réglementation environnementale peut constituer une expropriation indirecte."},
    {"tribunal": "CIRDI", "case_name": "Tecmed c. Mexique", "year": 2003,
     "topic": "expropriation_indirecte",
     "ratio": "Test de proportionnalité pour qualifier une expropriation indirecte."},
    {"tribunal": "CIRDI", "case_name": "Occidental c. Équateur", "year": 2012,
     "topic": "resiliation",
     "ratio": "Résiliation abusive — 1,77 Mrd USD accordés à l'investisseur."},
    {"tribunal": "Tribunal arbitral", "case_name": "Texaco/TOPCO c. Libye", "year": 1977,
     "topic": "souverainete",
     "ratio": "Nationalisation et souveraineté permanente : limites du droit international."},
    {"tribunal": "CIRDI", "case_name": "Burlington Resources c. Équateur", "year": 2012,
     "topic": "fiscalite",
     "ratio": "Modification fiscale unilatérale et droit de l'État sur sa fiscalité."},
    {"tribunal": "CIRDI", "case_name": "Biwater Gauff c. Tanzanie", "year": 2008,
     "topic": "transparence",
     "ratio": "Confidentialité vs droit du public à l'information dans les arbitrages d'investissement."},
    {"tribunal": "CIRDI", "case_name": "Suez c. Argentine", "year": 2010,
     "topic": "transparence",
     "ratio": "Reconnaissance de l'intérêt général et place de la société civile dans l'arbitrage."},
    {"tribunal": "Cour IADH", "case_name": "Saramaka c. Suriname", "year": 2007,
     "topic": "peuples_autochtones",
     "ratio": "Droit des peuples autochtones sur leurs terres et ressources, CLPE obligatoire."},
    {"tribunal": "Cour IADH", "case_name": "Sarayaku c. Équateur", "year": 2012,
     "topic": "consultation",
     "ratio": "Obligation de consultation préalable avant toute exploitation sur terres autochtones."},
    {"tribunal": "Commission africaine", "case_name": "SERAC c. Nigeria (Ogoniland)", "year": 2001,
     "topic": "art21_charte_africaine",
     "ratio": "Violation de l'Art. 21 de la Charte africaine — activités pétrolières Shell. Obligation positive de l'État."},
    {"tribunal": "CIJ", "case_name": "Roumanie c. Ukraine", "year": 2009,
     "topic": "zee",
     "ratio": "Délimitation ZEE et droits sur ressources en Mer Noire."},
    {"tribunal": "CIJ", "case_name": "Timor-Leste c. Australie", "year": 2014,
     "topic": "souverainete",
     "ratio": "Espionnage durant négociations pétrolières = violation de la souveraineté."},
    {"tribunal": "CIJ (avis consultatif)", "case_name": "Namibie", "year": 1971,
     "topic": "autodetermination",
     "ratio": "Droit des peuples à disposer librement de leurs ressources naturelles."},
]


GLOSSARY: List[Dict] = [
    {"term": "PSA / PSC", "definition": "Production Sharing Agreement / Contract — Contrat de partage de production entre l'État (propriétaire de la ressource) et l'entreprise (qui investit et exploite). Le profit oil est partagé selon une formule contractuelle."},
    {"term": "Cost Oil", "definition": "Quote-part de production destinée à rembourser les coûts d'exploration, développement et production. Plafonnée contractuellement (40-70% en général)."},
    {"term": "Profit Oil", "definition": "Production restante après déduction du cost oil, partagée entre l'État et l'entreprise selon les pourcentages contractuels."},
    {"term": "Royalty", "definition": "Redevance proportionnelle versée à l'État, calculée sur la valeur ou le volume de la production. Fourchettes : pétrole 5-25%, or 3-10%, gaz 3-15%."},
    {"term": "CLPE", "definition": "Consentement Libre, Préalable et Éclairé. Droit fondamental des peuples autochtones (Convention 169 OIT, DNUDPA) avant tout projet sur leurs terres."},
    {"term": "CIRDI / ICSID", "definition": "Centre International pour le Règlement des Différends relatifs aux Investissements (Banque Mondiale). Forum d'arbitrage investisseur-État."},
    {"term": "Back-in right", "definition": "Droit de l'État de prendre une participation dans le projet (souvent 10-20%) à des conditions définies à l'avance."},
    {"term": "Farm-out", "definition": "Cession totale ou partielle d'un permis ou d'un intérêt à un autre opérateur."},
    {"term": "Ring fence", "definition": "Cantonnement fiscal — chaque projet est imposé séparément, empêchant la compensation des pertes entre projets."},
    {"term": "Stabilisation clause", "definition": "Clause par laquelle l'État s'engage à ne pas modifier le régime juridique applicable au contrat. Peut être une atteinte à la souveraineté."},
    {"term": "Gross-up", "definition": "Clause par laquelle le payeur compense les retenues fiscales pour que le bénéficiaire reçoive le montant brut."},
    {"term": "Take-or-pay", "definition": "Clause obligeant l'acheteur à payer la quantité minimum convenue, qu'il enlève la marchandise ou non."},
    {"term": "Most Favoured Nation", "definition": "Clause de la nation la plus favorisée — l'État accorde à l'investisseur le traitement le plus favorable accordé à un autre."},
    {"term": "Negative Pledge", "definition": "Clause interdisant à l'État de constituer des sûretés sur les actifs au profit d'autres créanciers."},
    {"term": "Rebus sic stantibus", "definition": "Doctrine du changement fondamental de circonstances permettant la renégociation ou résiliation d'un traité (Art. 62 Convention de Vienne)."},
    {"term": "Pacta sunt servanda", "definition": "Les conventions doivent être respectées (Art. 26 Convention de Vienne). Principe fondamental du droit des contrats."},
    {"term": "Ratio decidendi", "definition": "Principe de droit qui justifie une décision judiciaire. Fonde la valeur jurisprudentielle d'un arrêt."},
    {"term": "Obiter dictum", "definition": "Remarque incidente d'un juge qui n'est pas nécessaire à la décision et n'a pas force de précédent."},
    {"term": "EIES", "definition": "Étude d'Impact Environnemental et Social — évaluation préalable obligatoire des impacts d'un projet."},
    {"term": "ITIE / EITI", "definition": "Initiative pour la Transparence des Industries Extractives — standard mondial de transparence des paiements."},
    {"term": "ZEE", "definition": "Zone Économique Exclusive — 200 milles nautiques où l'État côtier a des droits souverains sur les ressources (CNUDM)."},
    {"term": "Bonus de signature", "definition": "Paiement forfaitaire versé à l'État à la signature du contrat ou à l'octroi du permis."},
    {"term": "Stabilisation fiscale", "definition": "Engagement de l'État à ne pas modifier la fiscalité applicable au projet pendant une durée déterminée."},
    {"term": "Cadeau fiscal", "definition": "Manque à gagner pour l'État résultant d'exonérations excessives. Mesuré par l'élément don : 1 - (recettes État / valeur totale)."},
    {"term": "Doctrine Calvo", "definition": "Principe selon lequel un investisseur étranger doit accepter la juridiction des tribunaux nationaux et renoncer à la protection diplomatique."},
    {"term": "REJD", "definition": "Rapport d'Expertise Juridique Défendable — produit phare de RESOURCES-ANALYZER PRO. Rapport judiciairement défendable."},
    {"term": "SEC", "definition": "Score Environnemental de la Convention. 8 composantes pondérées, score sur 100."},
    {"term": "SSC", "definition": "Score Social de la Convention. 7 composantes pondérées, score sur 100."},
    {"term": "IDC", "definition": "Indice de Déséquilibre Contractuel. Mesure le déséquilibre entre droits/obligations État et entreprise."},
    {"term": "SOS", "definition": "Score de Souveraineté. 5 composantes, score sur 100."},
    {"term": "Souveraineté permanente", "definition": "Principe selon lequel chaque État dispose librement de ses ressources naturelles (Rés. ONU 1803, 1962)."},
    {"term": "Convention léonine", "definition": "Convention présentant un déséquilibre manifeste et excessif. Sanctionnée par nullité ou révision."},
    {"term": "Pollueur-payeur", "definition": "Principe selon lequel l'auteur de la pollution supporte les coûts de prévention et de réparation (Principe 16 Rio)."},
    {"term": "Précaution", "definition": "L'absence de certitude scientifique ne justifie pas l'inaction face à des risques graves et irréversibles (Principe 15 Rio)."},
    {"term": "OHADA", "definition": "Organisation pour l'Harmonisation en Afrique du Droit des Affaires. 17 États membres."},
    {"term": "CCJA", "definition": "Cour Commune de Justice et d'Arbitrage de l'OHADA. Cour suprême communautaire pour le droit des affaires."},
    {"term": "Vision minière africaine", "definition": "Cadre adopté par l'UA en 2009 pour transformer le secteur minier en levier de développement (contenu local, valeur ajoutée)."},
    {"term": "Resource-backed loan", "definition": "Prêt garanti par les ressources naturelles. Risque de double aliénation."},
    {"term": "Plan de réinstallation", "definition": "Plan d'indemnisation et de relocalisation des populations affectées par un projet (IFC PS5)."},
    {"term": "Fonds de développement local", "definition": "Mécanisme de redistribution d'une part des revenus aux communautés affectées."},
    {"term": "Contenu local", "definition": "Part minimale d'achats, d'emplois et de services nationaux dans l'exécution du projet."},
    {"term": "Article 21 Charte africaine", "definition": "Droit des peuples à disposer librement de leurs richesses et ressources. Récupération possible en cas de spoliation."},
    {"term": "PWYP", "definition": "Publish What You Pay — coalition mondiale d'ONG pour la transparence des paiements extractifs."},
    {"term": "NRGI", "definition": "Natural Resource Governance Institute — think tank de référence sur la gouvernance des ressources."},
    {"term": "Global Witness", "definition": "ONG d'investigation sur les liens entre ressources naturelles, conflits et corruption."},
    {"term": "Avenant", "definition": "Acte modificatif d'une convention. Doit respecter les conditions de forme et de fond du contrat initial."},
    {"term": "Concession", "definition": "Régime contractuel où l'entreprise est propriétaire de la ressource extraite, en contrepartie de royalties et impôts."},
    {"term": "Joint-Venture État-Entreprise", "definition": "Société mixte où l'État détient une participation aux côtés de l'entreprise."},
    {"term": "Risk Service Contract", "definition": "Contrat de services à risque — l'entreprise opère pour le compte de l'État et est rémunérée en cash, sans propriété de la ressource."},
    {"term": "Unitisation", "definition": "Accord d'exploitation conjointe d'un gisement transfrontalier."},
    {"term": "Bonus de production", "definition": "Paiement à l'État déclenché par l'atteinte de paliers de production."},
]
